name: Build all core packages

on:
  workflow_call:
    secrets:
      ccache_s3_endpoint:
      ccache_s3_bucket:
      ccache_s3_access_key:
      ccache_s3_secret_key:

jobs:
  build:
    name: Build Packages with external toolchain
    permissions:
      contents: read
      packages: read
      actions: write
    strategy:
      fail-fast: False
      matrix:
        include:
          - target: malta
            subtarget: be
          - target: x86
            subtarget: 64
    uses: ./.github/workflows/reusable_build.yml
    with:
      container_name: toolchain
      target: ${{ matrix.target }}
      subtarget: ${{ matrix.subtarget }}
      build_kernel: true
      build_all_kmods: true
      build_all_modules: true
      build_full: true
      ccache_type: packages
      upload_ccache_cache: ${{ github.repository_owner == 'RouterBucket' }}

  upload-ccache-cache-in-s3:
    if: github.event_name == 'push' && github.repository_owner == 'RouterBucket'
    name: Upload ccache cache to s3
    needs: build
    strategy:
       fail-fast: False
       matrix:
        include:
          - target: malta
            subtarget: be
          - target: x86
            subtarget: 64
    secrets:
      s3_endpoint: ${{ secrets.ccache_s3_endpoint }}
      s3_bucket: ${{ secrets.ccache_s3_bucket }}
      s3_access_key: ${{ secrets.ccache_s3_access_key }}
      s3_secret_key: ${{ secrets.ccache_s3_secret_key }}
    uses: ./.github/workflows/reusable_upload-file-s3.yml
    with:
      download_id: ${{ matrix.target }}-${{ matrix.subtarget }}-ccache-cache
      filename: ccache-packages-${{ matrix.target }}-${{ matrix.subtarget }}.tar

