name: Build host tools

on:
  workflow_call:

jobs:
  build-macos-latest:
    name: Build tools with macos latest
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: immortalwrt

      - name: Setup MacOS
        run: |
          echo "WORKPATH=/Volumes/ImmortalWrt" >> "$GITHUB_ENV"
          hdiutil create -size 20g -type SPARSE -fs "Case-sensitive HFS+" -volname ImmortalWrt ImmortalWrt.sparseimage
          hdiutil attach ImmortalWrt.sparseimage
          mv "$GITHUB_WORKSPACE/immortalwrt" /Volumes/ImmortalWrt/

      - name: Install required prereq on MacOS
        working-directory: ${{ env.WORKPATH }}/immortalwrt
        run: |
          brew install \
            automake \
            coreutils \
            diffutils \
            findutils \
            gawk \
            git-extras \
            gnu-getopt \
            gnu-sed \
            grep \
            make

            echo "/bin" >> "$GITHUB_PATH"
            echo "/sbin/Library/Apple/usr/bin" >> "$GITHUB_PATH"
            echo "/usr/bin" >> "$GITHUB_PATH"
            echo "/usr/local/bin" >> "$GITHUB_PATH"
            echo "/usr/local/opt/coreutils/bin" >> "$GITHUB_PATH"
            echo "/usr/local/opt/findutils/libexec/gnubin" >> "$GITHUB_PATH"
            echo "/usr/local/opt/gettext/bin" >> "$GITHUB_PATH"
            echo "/usr/local/opt/gnu-getopt/bin" >> "$GITHUB_PATH"
            echo "/usr/local/opt/make/libexec/gnubin" >> "$GITHUB_PATH"
            echo "/usr/local/opt/make/libexec/gnubin" >> "$GITHUB_PATH"
            echo "/usr/sbin" >> "$GITHUB_PATH"

      - name: Make prereq
        working-directory: ${{ env.WORKPATH }}/immortalwrt
        run: make defconfig

      - name: Build tools MacOS
        working-directory: ${{ env.WORKPATH }}/immortalwrt
        run: make tools/install -j$(nproc) BUILD_LOG=1 || ret=$? .github/workflows/scripts/show_build_failures.sh

      - name: Upload logs
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: macos-latest-logs
          path: ${{ env.WORKPATH }}/immortalwrt/logs

      - name: Upload config
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: macos-latest-config
          path: ${{ env.WORKPATH }}/immortalwrt/.config

  build-linux-buildbot:
    name: Build tools with buildbot container
    uses: ./.github/workflows/reusable_build-tools.yml
